from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def test_database_sql_is_postgres_compatible():
    files = [
        ROOT / 'backend' / 'database' / 'sgs_usuarios_db.sql',
        ROOT / 'backend' / 'database' / 'sgs_infraestructura_db.sql',
        ROOT / 'backend' / 'database' / 'sgs_operaciones_db.sql',
    ]

    for file_path in files:
        sql = file_path.read_text(encoding='utf-8')

        assert 'AUTO_INCREMENT' not in sql.upper()
        assert 'CREATE DATABASE' not in sql.upper()
        assert 'USE ' not in sql.upper()
        assert 'ENUM(' not in sql.upper()
        assert 'GENERATED BY DEFAULT AS IDENTITY' in sql.upper()
