CREATE TABLE IF NOT EXISTS salon (
    id_salon INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    capacidad INTEGER NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'disponible'
        CHECK (estado IN ('disponible', 'mantenimiento', 'ocupado')),
    ubicacion VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_salon_estado
    ON salon (estado);