CREATE TABLE IF NOT EXISTS reserva (
    id_reserva INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'pendiente_confirmacion'
        CHECK (estado IN ('confirmada', 'cancelada', 'pendiente_confirmacion')),
    id_docente INTEGER NOT NULL,
    id_salon INTEGER NOT NULL,
    id_operador INTEGER NULL,
    fecha_notificacion TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS cola_espera (
    id_cola INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_salon INTEGER NOT NULL,
    id_docente INTEGER NOT NULL,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reserva_fecha
    ON reserva (fecha);

CREATE INDEX IF NOT EXISTS idx_cola_espera_salon
    ON cola_espera (id_salon);